<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="3">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="960" startPos="1187" endPos="1187" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Program Files (x86)\Notepad++\change.log" backupFilePath="C:\Users\ethan\AppData\Roaming\Notepad++\backup\change.log@2021-09-30_112446" originalFileLastModifTimestamp="-837341696" originalFileLastModifTimestampHigh="30820775" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7864439" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="63" xOffset="0" scrollWidth="568" startPos="4026" endPos="4026" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\new-function\.gitattributes" backupFilePath="C:\Users\ethan\AppData\Roaming\Notepad++\backup\.gitattributes@2021-09-30_112535" originalFileLastModifTimestamp="973362220" originalFileLastModifTimestampHigh="30914012" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="15" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="48" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\.gitignore" backupFilePath="" originalFileLastModifTimestamp="577877340" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1936879984" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="57" xOffset="0" scrollWidth="616" startPos="2174" endPos="2282" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\frag.glsl" backupFilePath="C:\Users\ethan\AppData\Roaming\Notepad++\backup\frag.glsl@2021-09-30_113551" originalFileLastModifTimestamp="577967361" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="4259930" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="0" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\LICENSE" backupFilePath="" originalFileLastModifTimestamp="577887337" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1927614127" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="0" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\LICENSE-FONT.txt" backupFilePath="" originalFileLastModifTimestamp="577897335" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="15628520" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="896" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="XML" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\MandelbrotMusic.vcxproj" backupFilePath="" originalFileLastModifTimestamp="577907346" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7365971" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="936" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="XML" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\MandelbrotMusic.vcxproj.filters" backupFilePath="" originalFileLastModifTimestamp="577917343" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="712" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="XML" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\MandelbrotMusic.vcxproj.user" backupFilePath="" originalFileLastModifTimestamp="577927347" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="0" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\RobotoMono-Medium.ttf" backupFilePath="" originalFileLastModifTimestamp="577947336" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="472" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="C++" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\Main.cpp" backupFilePath="" originalFileLastModifTimestamp="577907346" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1916210941" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="2440" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="Markdown (Default)" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\README.md" backupFilePath="" originalFileLastModifTimestamp="577927347" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="95" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="520" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="Normal Text" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\vert.glsl" backupFilePath="" originalFileLastModifTimestamp="577977353" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7471201" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="776" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="C++" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\WinAudio.cpp" backupFilePath="" originalFileLastModifTimestamp="577957364" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="0" lang="C++" encoding="-1" userReadOnly="no" filename="C:\Users\ethan\Documents\GitHub\FractalSoundExplorer\WinAudio.h" backupFilePath="" originalFileLastModifTimestamp="577957364" originalFileLastModifTimestampHigh="30914014" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="16" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
